/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpikoinoniaRouteImport } from './routes/epikoinonia'
import { Route as EpitychiesRouteImport } from './routes/epitychies'
import { Route as FrontistirioRouteImport } from './routes/frontistirio'
import { Route as MathimataRouteImport } from './routes/mathimata'
import { Route as AdminLandingRouteImport } from './routes/admin/landing'
import { Route as SitemapXmlRouteImport } from './routes/sitemap.xml'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpikoinoniaRoute = EpikoinoniaRouteImport.update({
  id: '/epikoinonia',
  path: '/epikoinonia',
  getParentRoute: () => rootRouteImport,
} as any)
const EpitychiesRoute = EpitychiesRouteImport.update({
  id: '/epitychies',
  path: '/epitychies',
  getParentRoute: () => rootRouteImport,
} as any)
const FrontistirioRoute = FrontistirioRouteImport.update({
  id: '/frontistirio',
  path: '/frontistirio',
  getParentRoute: () => rootRouteImport,
} as any)
const MathimataRoute = MathimataRouteImport.update({
  id: '/mathimata',
  path: '/mathimata',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLandingRoute = AdminLandingRouteImport.update({
  id: '/admin/landing',
  path: '/admin/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapXmlRoute = SitemapXmlRouteImport.update({
  id: '/sitemap/xml',
  path: '/sitemap/xml',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/epikoinonia': typeof EpikoinoniaRoute
  '/epitychies': typeof EpitychiesRoute
  '/frontistirio': typeof FrontistirioRoute
  '/mathimata': typeof MathimataRoute
  '/admin/landing': typeof AdminLandingRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/epikoinonia': typeof EpikoinoniaRoute
  '/epitychies': typeof EpitychiesRoute
  '/frontistirio': typeof FrontistirioRoute
  '/mathimata': typeof MathimataRoute
  '/admin/landing': typeof AdminLandingRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/epikoinonia': typeof EpikoinoniaRoute
  '/epitychies': typeof EpitychiesRoute
  '/frontistirio': typeof FrontistirioRoute
  '/mathimata': typeof MathimataRoute
  '/admin/landing': typeof AdminLandingRoute
  '/sitemap/xml': typeof SitemapXmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/epikoinonia'
    | '/epitychies'
    | '/frontistirio'
    | '/mathimata'
    | '/admin/landing'
    | '/sitemap/xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/epikoinonia'
    | '/epitychies'
    | '/frontistirio'
    | '/mathimata'
    | '/admin/landing'
    | '/sitemap/xml'
  id:
    | '__root__'
    | '/'
    | '/epikoinonia'
    | '/epitychies'
    | '/frontistirio'
    | '/mathimata'
    | '/admin/landing'
    | '/sitemap/xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EpikoinoniaRoute: typeof EpikoinoniaRoute
  EpitychiesRoute: typeof EpitychiesRoute
  FrontistirioRoute: typeof FrontistirioRoute
  MathimataRoute: typeof MathimataRoute
  AdminLandingRoute: typeof AdminLandingRoute
  SitemapXmlRoute: typeof SitemapXmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epikoinonia': {
      id: '/epikoinonia'
      path: '/epikoinonia'
      fullPath: '/epikoinonia'
      preLoaderRoute: typeof EpikoinoniaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/epitychies': {
      id: '/epitychies'
      path: '/epitychies'
      fullPath: '/epitychies'
      preLoaderRoute: typeof EpitychiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/frontistirio': {
      id: '/frontistirio'
      path: '/frontistirio'
      fullPath: '/frontistirio'
      preLoaderRoute: typeof FrontistirioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mathimata': {
      id: '/mathimata'
      path: '/mathimata'
      fullPath: '/mathimata'
      preLoaderRoute: typeof MathimataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/landing': {
      id: '/admin/landing'
      path: '/admin/landing'
      fullPath: '/admin/landing'
      preLoaderRoute: typeof AdminLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap/xml': {
      id: '/sitemap/xml'
      path: '/sitemap/xml'
      fullPath: '/sitemap/xml'
      preLoaderRoute: typeof SitemapXmlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EpikoinoniaRoute: EpikoinoniaRoute,
  EpitychiesRoute: EpitychiesRoute,
  FrontistirioRoute: FrontistirioRoute,
  MathimataRoute: MathimataRoute,
  AdminLandingRoute: AdminLandingRoute,
  SitemapXmlRoute: SitemapXmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
